format = "$character"
right_format = "$cmd_duration$all$username$hostname"
add_newline = false

[aws]
symbol = "îŒ½  "
format = "|[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)"

[buf]
symbol = "ï’ "
format = "|[$symbol]($style)"

[c]
symbol = "î˜ "
format = "|[$symbol]($style)"

[conda]
symbol = "î˜† "
format = "|[$symbol$environment]($style)"
ignore_base = false

[dart]
symbol = "î˜ "
format = "|[$symbol]($style)"

[directory]
read_only = "ï€£ "
format = "[$read_only]($read_only_style)[$path]($style)"
read_only_style = "bright-yellow"

[docker_context]
symbol = "ïŒˆ "
format = "|[$symbol$context]($style)"

[elixir]
symbol = "î‰µ "
format = "|[$symbol]($style)"

[elm]
symbol = "î˜¬ "
format = "|[$symbol]($style)"

# [fossil_branch]
# symbol = "ï˜ "
# format = "|[$symbol$branch]($style)"

[git_branch]
symbol = "îœ¥"
format = "|[$symbol$branch]($style)"

[golang]
symbol = "î˜§ "
format = "|[$symbol]($style)"

[guix_shell]
symbol = "ïŒ¥ "
format = "|[$symbol]($style)"

[haskell]
symbol = "î· "
format = "|[$symbol]($style)"

[haxe]
symbol = "âŒ˜ "
format = "|[$symbol]($style)"

[hg_branch]
symbol = "ï˜ "
format = "|[$symbol$branch]($style)"

[hostname]
ssh_symbol = "@"
format = "[$ssh_symbol$hostname]($style)"

[java]
symbol = "î‰– "
format = "|[$symbol]($style)"

[julia]
symbol = "î˜¤ "
format = "|[$symbol]($style)"

[lua]
symbol = "î˜  "
format = "|[$symbol]($style)"

[memory_usage]
symbol = "ó°› "
format = "|$symbol[$ram( | $swap)]($style)"

[meson]
symbol = "ï¨¶ "
format = "|[$symbol]($style)"

[nim]
symbol = "î™· "
format = "|[$symbol]($style)"

[nix_shell]
symbol = "ïŒ“ "
format = "|[$symbol$state( \\($name\\))]($style)"

[nodejs]
symbol = "ó°™ "
format = "|[$symbol]($style)"

[os]
format = "|[$symbol]($style)"

[os.symbols]
# Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
# Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "? "
Gentoo = "ïŒ "
HardenedBSD = "? "
Illumos = "ïŒ¦ "
Linux = "ïŒš "
# Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïŒ¨ "
openSUSE = "ïŒ” "
OracleLinux = "? "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ïŒ­ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "? "
Windows = "î˜ª "

[package]
symbol = "î¬© "
format = "|[$symbol]($style)"
disabled = true

# [pijul_channel]
# symbol = "ğŸªº "
# format = "|[$symbol$channel]($style)"

[python]
symbol = "îœ¼ "
format = "(|[$symbol$virtualenv]($style))"

[rlang]
symbol = "îšŠ "
format = "|[$symbol]($style)"

[ruby]
symbol = "î‘ "
format = "|[$symbol]($style)"

[rust]
symbol = "î¨ "
format = "|[$symbol]($style)"

[scala]
symbol = "îœ· "
format = "|[$symbol]($style)"

[spack]
symbol = "ğŸ…¢ "
format = "|[$symbol$environment]($style)"

[bun]
format = "|[$symbol]($style)"

[cmake]
format = "|[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)|"

[cobol]
format = "|[$symbol]($style)"

[crystal]
format = "|[$symbol]($style)"

[daml]
format = "|[$symbol]($style)"

[deno]
format = "|[$symbol]($style)"

[dotnet]
format = "|[$symbol(ó°“¾ $tfm )]($style)"

[erlang]
format = "|[$symbol]($style)"

# [fennel]
# format = "|[$symbol]($style)"

[gcloud]
format = "|[$symbol$account(@$domain)(\\($region\\))]($style)"

# [gradle]
# format = "|[$symbol]($style)"

[helm]
format = "|[$symbol]($style)"

[kotlin]
format = "|[$symbol]($style)"

[kubernetes]
format = "|[$symbol$context( \\($namespace\\))]($style)"

[ocaml]
format = "|[$symbol(\\($switch_indicator$switch_name\\) )]($style)"

[opa]
format = "|[$symbol]($style)"

[openstack]
format = "|[$symbol$cloud(\\($project\\))]($style)"

[perl]
format = "|[$symbol]($style)"
disabled = true

[php]
format = "|[$symbol]($style)"

[pulumi]
format = "|[$symbol$stack]($style)"

[purescript]
format = "|[$symbol]($style)"

[raku]
format = "|[$symbol]($style)"

[red]
format = "|[$symbol]($style)"

[sudo]
format = "|[as $symbol]"

[swift]
format = "|[$symbol]($style)"

[terraform]
format = "|[$symbol$workspace]($style)"

[time]
format = "|[$time]($style)"

[username]
format = "|[$user]($style)"

[vagrant]
format = "|[$symbol]($style)"

[vlang]
format = "|[$symbol]($style)"

[zig]
format = "|[$symbol]($style)"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"
